DEFRA/biodiversity-net-gain-service

lerna.json, packages/azure-functions/package-lock.json, packages/azure-functions/package.json, packages/azure-storage-test-utils/package-lock.json, packages/azure-storage-test-utils/package.json, packages/azurite-bootstrap-service/package-lock.json, packages/azurite-bootstrap-service/package.json, packages/connectors-lib/package-lock.json, packages/connectors-lib/package.json, packages/connectors-lib/src/__tests__/azure-blob-storage-connector.spec.js, packages/connectors-lib/src/azure-blob-storage-connector.js, packages/document-service/package-lock.json, packages/document-service/package.json, packages/errors-lib/package-lock.json, packages/errors-lib/package.json, packages/geoprocessing-service/package-lock.json, packages/geoprocessing-service/package.json, packages/utils-lib/package-lock.json, packages/utils-lib/package.json, packages/webapp/package-lock.json, packages/webapp/package.json
https://eaflood.atlassian.net/browse/BNGP-1738
=> BNGP-1738-blob-deletion-guard

packages/bng-metric-service/src/helpers/extractors/extractionconfig/configuration.js, packages/webapp/src/routes/developer/upload-metric-file.js
Modified extraction config file and also rounded up decimal place to 1 as per prototype
=> Fixed metric extraction minor issue

packages/bng-metric-service/src/helpers/extractors/extractionconfig/configuration.js, packages/webapp/src/routes/developer/upload-metric-file.js
Reverts DEFRA/biodiversity-net-gain-service#222
=> Revert "Fixed metric extraction minor issue"

packages/webapp/src/routes/__tests__/developer/eligibility-england-no.spec.js, packages/webapp/src/routes/__tests__/developer/eligibility-england.spec.js, packages/webapp/src/routes/__tests__/developer/eligibility-landowner-consent.spec.js, packages/webapp/src/routes/developer/eligibility-england-no.js, packages/webapp/src/routes/developer/eligibility-england.js, packages/webapp/src/routes/developer/eligibility-landowner-consent.js, packages/webapp/src/utils/developer-constants.js, packages/webapp/src/views/developer/eligibility-england-no.html, packages/webapp/src/views/developer/eligibility-england.html, packages/webapp/src/views/developer/eligibility-landowner-consent.html, packages/webapp/src/views/developer/routing-result.html
This PR includes changes of eligibility question
_Is the biodiversity gain site you're using to record off-site gain for a development project in England?_
=> Feature/BNGP-2187: Eligibility

packages/webapp/src/routes/__tests__/developer/eligibility-metric.spec.js, packages/webapp/src/routes/__tests__/developer/eligibility-result.spec.js, packages/webapp/src/routes/developer/eligibility-metric.js, packages/webapp/src/routes/developer/eligibility-result.js, packages/webapp/src/utils/developer-constants.js, packages/webapp/src/views/developer/eligibility-metric.html, packages/webapp/src/views/developer/eligibility-result.html
This PR includes the following question about eligibility;
- Do you have a completed Biodiversity metric 4.0 file?
=> Feature/BNGP-2192: Eligibility metric

packages/webapp/client/js/pages/developer/email-entry.js, packages/webapp/src/routes/__tests__/developer/email-entry.spec.js, packages/webapp/src/routes/developer/email-entry.js, packages/webapp/src/views/developer/email-entry.html
Includes changes for existing page of additional email address
- Optimized code
- Added duplicate email address check
- Added script to validate number of 1 fields rows
- Improved test coverage
=> Feature/BNGP-2680: Add name to additional email addresses

packages/webapp/src/views/developer-form-layout.html, packages/webapp/src/views/developer/check-metric-file.html, packages/webapp/src/views/developer/confirm-development-details.html, packages/webapp/src/views/developer/upload-metric-file.html
As per the new prototype service name is changed to **Manage biodiversity gains** from _Record biodiversity gains_
=> updated page title of the service to <<Manage biodiversity gains>>

packages/webapp/src/routes/__tests__/developer/confirm-off-site-gain.spec.js, packages/webapp/src/routes/developer/confirm-off-site-gain.js
Updated all the references of Register reference number to Off-site references
=> BNGP-2978 : Updating references of Register Reference Number

packages/webapp/src/views/developer/biodiversity-gain-site-number.html, packages/webapp/src/views/developer/check-answers.html, packages/webapp/src/views/developer/confirm-development-details.html, packages/webapp/src/views/developer/confirm-off-site-gain.html, packages/webapp/src/views/developer/consent-agreement-upload.html, packages/webapp/src/views/developer/details-confirm.html, packages/webapp/src/views/developer/details-email-confirm.html, packages/webapp/src/views/developer/details-email.html, packages/webapp/src/views/developer/details-name.html, packages/webapp/src/views/developer/eligibility-england.html, packages/webapp/src/views/developer/eligibility-landowner-consent.html, packages/webapp/src/views/developer/eligibility-metric.html, packages/webapp/src/views/developer/eligibility-results.html, packages/webapp/src/views/developer/email-entry.html, packages/webapp/src/views/developer/routing-register.html, packages/webapp/src/views/developer/routing-result.html, packages/webapp/src/views/developer/upload-metric-file.html
Attribute id and test-id added to all continue buttons in DJ
=> Attribute id and test-id added to all continue buttons in DJ

packages/bng-metric-service/src/helpers/extractors/__tests__/bng-metric-single-data-extractor.spec.js, packages/bng-metric-service/src/helpers/extractors/validation-config/are-offsite-totals-correct.js
Fix the bug reported in ticket https://eaflood.atlassian.net/browse/BNGP-2800
Floating point rounding error when checking total values from excel metric file. Add a tolerance to the check to cope with floating point rounding errors.
=> BNGP 2800 Rounding Error Bug

packages/webapp/src/views/layout.html
Added condition in layout for error title
=> BNGP-3310-title-change-on-error

packages/webapp/src/views/land/check-and-submit.html
Added declaration to the check and submit page
=> Feature/BNGP-3157: check and submit page - add Declaration to bottom of the page 

packages/webapp/src/routes/land/clients-name.js
4 bugs
- Middlename not being stored correctly
- Errors not being processed for the header error message
- values not being displayed on page GET
- Values lost on error
=> BNGP-3614 bug fixes

packages/webapp/client/js/core.js, packages/webapp/client/sass/application.scss, packages/webapp/src/views/layout.html
https://eaflood.atlassian.net/browse/BNGP-4184
=> BNGP-4184 Small prod ready tasks

packages/webapp/src/utils/__tests__/application.spec.js, packages/webapp/src/utils/application.js
Add broad habitat to habitat type in payload for d1, d2, d3 sheets
https://eaflood.atlassian.net/browse/BNGP-4186
=> BNGP-4186 Add broad habitat to habitat type

packages/webapp/src/views/land/check-habitat-baseline.html
=> BNGP-4314: typo updated for link

packages/webapp/src/routes/__tests__/credits-purchase/add-statutory-biodiversity-credits.spec.js, packages/webapp/src/routes/__tests__/credits-purchase/estimated-cost-statutory-biodiversity-credits.spec.js, packages/webapp/src/routes/credits-purchase/add-statutory-biodiversity-credits.js, packages/webapp/src/routes/credits-purchase/estimated-cost-statutory-biodiversity-credits.js, packages/webapp/src/utils/credits-purchase-constants.js, packages/webapp/src/views/credits-purchase/add-statutory-biodiversity-credits.html, packages/webapp/src/views/credits-purchase/estimated-cost-statutory-biodiversity-credits.html
=> BNGP-2814 and BNGP-3441: Add credits to purchase and calculate cost

packages/webapp/src/views/credits-purchase/check-defra-account-details.html
https://eaflood.atlassian.net/browse/BNGP-4777
This change updates content for company details on the check your defra account details page when on the credits purchase journey.
=> BNGP-4777: Content update company details

packages/webapp/src/routes/developer/development-projects.js, packages/webapp/src/routes/land/biodiversity-gain-sites.js, packages/webapp/src/utils/config.js, packages/webapp/src/utils/constants.js, packages/webapp/src/views/common/applications.html, packages/webapp/src/views/developer/development-projects.html, packages/webapp/src/views/land/biodiversity-gain-sites.html
…var for both URLs with a fallback
=> BNGP-5221 Amendments and Removals - dev work on FE service to add links to guidance on dashboard page(s) and start page

packages/webapp/src/routes/__tests__/combined-case/match-habitats.spec.js, packages/webapp/src/routes/combined-case/match-habitats.js, packages/webapp/src/views/combined-case/match-habitats.html
https://eaflood.atlassian.net/browse/BNGP-5325
This change updates the habitat matching page to match v4 of the design content.
=> BNGP-5325: Update habitat matching page content

packages/webapp/src/payment/constants.js, packages/webapp/src/routes/__tests__/combined-case/application-submitted.spec.js, packages/webapp/src/routes/__tests__/combined-case/check-and-submit.spec.js, packages/webapp/src/routes/combined-case/application-submitted.js, packages/webapp/src/routes/combined-case/check-and-submit.js, packages/webapp/src/utils/combined-case-application-validation.js, packages/webapp/src/utils/combined-case-application.js, packages/webapp/src/utils/combined-case-constants.js, packages/webapp/src/views/application-submitted.html
https://eaflood.atlassian.net/browse/BNGP-5356
This change adds the combined case confirmation page route and links to the shared view. It also adds the “discharge planning section”.
=> BNGP-5356: Update CC confirmation page

packages/webapp/src/utils/__tests__/combined-case-application.spec.js, packages/webapp/src/utils/combined-case-application-validation.js, packages/webapp/src/utils/combined-case-application.js
Reverts DEFRA/biodiversity-net-gain-service#865
=> BNGP-5465: Revert "BNGP-5455: Tweak combined case payload to match backend processing"

packages/webapp/src/routes/land/ownership-proof-list.js
https://eaflood.atlassian.net/browse/BNGP-5464
=> BNGP-5464: Fix `DAC_Non-descriptive_links_01`

packages/webapp/src/views/common/add-individual-name.html, packages/webapp/src/views/land/add-landowner-organisation.html
https://eaflood.atlassian.net/browse/BNGP-5468
=> BNGP-5468: Fix `DAC_Incorrect_autocomplete_attribute_01`

packages/webapp/src/journey-validation/combined-case/legal-agreement.js, packages/webapp/src/journey-validation/registration/legal-agreement.js, packages/webapp/src/journey-validation/shared/legal-agreement.js, packages/webapp/src/routes/__tests__/land/any-other-landowners.spec.js, packages/webapp/src/routes/land/add-landowner-organisation.js, packages/webapp/src/routes/land/check-landowners.js, packages/webapp/src/routes/land/need-add-all-landowners.js
https://eaflood.atlassian.net/browse/BNGP-5489
=> BNGP-5489: Fix user is incorrectly returned from "Add legal agreement" journey

packages/webapp/src/journey-validation/allocation/task-sections.js, packages/webapp/src/journey-validation/credits-purchase/task-sections.js, packages/webapp/src/routes/__tests__/credits-purchase/tasklist.spec.js, packages/webapp/src/routes/__tests__/developer/tasklist.spec.js, packages/webapp/src/utils/developer-task-list.js
https://eaflood.atlassian.net/browse/BNGP-5509
Typo 'devlopment' appears in multiple places. This change fixes the typo throughout the codebase with no regressions.
=> BNGP-5509: Fix typo 'devlopment'
